# Generated by Django 3.2.6 on 2021-10-30 13:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorter',
            name='name',
        ),
        migrations.AddField(
            model_name='sorter',
            name='unsortedList',
            field=models.CharField(default=[1, 2, 3], max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
