# Generated by Django 3.2.6 on 2021-10-30 15:59

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0009_alter_sorter_unsortedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorter',
            name='sortedList',
            field=models.CharField(default='3,1,2', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
