# Generated by Django 3.2.6 on 2021-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0010_sorter_sortedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorter',
            name='sortedList',
            field=models.CharField(default='3,1,2', max_length=50),
        ),
    ]
