# Generated by Django 3.2.6 on 2021-10-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0011_alter_sorter_sortedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorter',
            name='sortedList',
        ),
    ]
